parameters:
  configuration: Debug
  testDisplayName: xunit.console.exe *.Tests.dll
  testCommand: "mono --server xunit.runner.console.*/tools/net471/xunit.console.exe"
  testArguments: -verbose -parallel none
  testTimeoutInMinutes: 12
  publicTestResult: true

steps:

- task: Bash@3
  displayName: hooks/check-bom
  inputs:
    targetType: filePath
    filePath: hooks/check-bom

- task: NuGetCommand@2
  displayName: nuget install xunit.runner.console
  inputs:
    command: custom
    arguments: install xunit.runner.console

- task: CmdLine@2
  displayName: msbuild /restore
  inputs:
    script: |
      msbuild \
        /restore \
        /p:Configuration=${{ parameters.configuration }} \
        /p:SkipSonar=true

- task: Bash@3
  displayName: List all test assemblies
  inputs:
    targetType: inline
    script: |
      echo -n '##vso[task.setvariable variable=testAssemblies]'
      for f in *.Tests; do
        printf '%q ' \
          "`pwd`/$f"/bin/${{ parameters.configuration }}/net*/"$f".dll
      done

- ${{ if eq(parameters.publicTestResult, false) }}:
  - task: CmdLine@2
    displayName: ${{ parameters.testDisplayName }}
    inputs:
      script: |
        ${{ parameters.testCommand }} \
          $(testAssemblies) \
          ${{ parameters.testArguments }}
    env:
      TURN_SERVER_URL: ${{ parameters.turnServerUrl }}
      MONO_THREADS_SUSPEND: preemptive
    timeoutInMinutes: ${{ parameters.testTimeoutInMinutes }}

- ${{ if eq(parameters.publicTestResult, true) }}:
  - task: CmdLine@2
    displayName: ${{ parameters.testDisplayName }}
    inputs:
      script: |
        ${{ parameters.testCommand }} \
          $(testAssemblies) \
          ${{ parameters.testArguments }} \
          -xml "$(Agent.TempDirectory)/xunit.xml"
    env:
      TURN_SERVER_URL: ${{ parameters.turnServerUrl }}
      MONO_THREADS_SUSPEND: preemptive
    timeoutInMinutes: ${{ parameters.testTimeoutInMinutes }}
  - task: PublishTestResults@2
    inputs:
      testRunner: XUnit
      testResultsFiles: '$(Agent.TempDirectory)/xunit.xml'
