on: push
name: docker-image
jobs:
  build_and_push:
    runs-on: ubuntu-18.04
    steps:
    - name: checkout
      uses: actions/checkout@v2.3.4
    # TODO: give images tags of release versions
    - name: build
      run: |
        docker build \
          -f Dockerfile.explorer \
          -t planetariumhq/libplanet-explorer:git-${{ github.sha }} \
          .
    - name: push
      run: |
        if [[ "${{ secrets.DOCKER_USERNAME }}" != "" &&
              "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" != "" ]]; then
          docker login \
            --username "${{ secrets.DOCKER_USERNAME }}" \
            --password "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
          docker push \
            planetariumhq/libplanet-explorer:git-${{ github.sha }}
        fi
